### ISSUE TITLE
Feature Request: brightness control

### ISSUE THREAD

**Issue by njh** [revk/ESP32-LED#10]
Please can you an overall brightness control, which scales the output of running apps before passing the values to the LED strip?

* Slider on web control (between 0 and 100%)
* Command and status of brightness via MQTT

Thanks!

**Comment by revk** [comment]
MQTT has a brightness and HA sets that anyway.

There is also a global max setting for each of R G and B in settings.

**Comment by njh** [comment]
I don't know why I am so resistant to installing HomeAssistant.
I am running out of excuses not to install it.

I am attempting to use [HomeBridge](https://homebridge.io/) + [MQTT Thing](https://github.com/arachnetech/homebridge-mqttthing) to do basic RGBW LED strip control.

**Comment by revk** [comment]
Ok but brightness is still a setting at MQTT and there are still the global settings.

<img width="585" alt="Screenshot 2024-10-27 at 15 41 24" src="https://github.com/user-attachments/assets/bd9c01ad-e55b-40cd-810f-050ed643f47f">
