### ISSUE TITLE
brightness rangle values

### ISSUE THREAD

**Issue by tomchiverton** [revk/ESP32-LED#5]
Neither the overview docs here or the web GUI specify what the allowed range/units are for brightness.

Is it 0-100 (percent), voltage (0-3.3), ...

**Comment by revk** [comment]
I'll have to check, it is whatever HA expects.

**Comment by revk** [comment]
Looks like 0-255

**Comment by tomchiverton** [comment]
Would you be open to patch to at least Overview.md to say this ?

I'd love for the web interface to enforce this too, but don't see where I might set that

**Comment by revk** [comment]
I can update the `.md` yeh.
