### ISSUE TITLE
Missing Case

### ISSUE THREAD

**Issue by b-bilko** [revk/ESP32-LED#6]
Hi,

I have a board on order from amazon, and came here looking for the mentioned case design. 

Can you add this to the repo for easy reference? 

Many thanks!

**Comment by revk** [comment]
Surley
https://github.com/revk/ESP32-LED/blob/main/PCB/LED/LED-Screw.stl
and
https://github.com/revk/ESP32-LED/blob/main/PCB/LED/LED.stl
