### ISSUE TITLE
Board flashing, but not showing AP.

### ISSUE THREAD

**Issue by b-bilko** [revk/ESP32-LED#7]
Hi,

I have my board from Amazon, and flashed it with WLED today. 

First use I was getting lights flashing blue and green lights, but not I'm not getting any lights. 

It still shows up as a Com port, and WLED seems to flash ok, but I don't get the AP for next stage config. 

Do I have a faulty board, or is there something I can do to recover it?

**Comment by revk** [comment]
If you flash WLED it is kind of down to WLED - the processor with WiFi is self contained, if it shows as a com port, it means it is powered correctly, so not a lot that could be faulty (apart from code).

You flashed the right WLED build? ESP32 S3 4M ?

**Comment by jsouto77** [comment]
Im having exactly the same issue as thee OP . I have flashed every build of ESP32 S3 4M  and it just doesn't work unfortunately. It's a good thing I only bought 1 to try and not the whole 4 that were available. 

Was this actually tested before advertising WLED compatibility?

**Comment by revk** [comment]
We have them working with WLED, no problem. Flashed using the web based WLED flasher, using the ESP32S3 4M build. I have flashed them myself and had them working.

**Comment by jsouto77** [comment]
> We have them working with WLED, no problem. Flashed using the web based WLED flasher, using the ESP32S3 4M build. I have flashed them myself and had them working.

Ive used all the files you said from https://wled-install.github.io  to no avail. Flashing the your bin file back in does revive the controller to a working state as per received.

**Comment by revk** [comment]
Did you try using their web based flasher? That is literally what I did, and just worked.

**Comment by jsouto77** [comment]
> Did you try using their web based flasher? That is literally what I did, and just worked.

Yes. Used https://install.wled.me/  which only allows release selection. This was actually the first tool I used.

**Comment by revk** [comment]
This is what I have just tried...

- I went to https://wled-install.github.io in Chrome
- Selected English
- Selected ESP32-S3 (4M Flash)
- Clicked Agree
- Clicked Install
- Selected USB JTAG/serial debug unit (cu.usbmodem71201)
- Selected INSTALL WLED (ESP32-S3, 4M)
- Selected INSTALL
- Waited while it installed

It then appeared as a WiFi AP, so working fine.

![IMG_5642](https://github.com/user-attachments/assets/ed6f7bfe-e22a-49f1-aa6d-1646bce9cd6a)

![IMG_5643](https://github.com/user-attachments/assets/88a9c407-c6e6-40b3-a009-2498d11ae0fc)

**Comment by jsouto77** [comment]
I have tried the exact same multiple times. It flashes but the device becomes dead and no lights and does not ask to configure at the end. I have also unplugged and plugged back in and left it for a while but still no lights on board and no WLED wifi to be seen. 

If I flash back with your bin file, it installs with an error at the end saying failed but after unplugging and plugging back in the lights on the device come on and I get the wifi for it just as when received and works fine.

**Comment by revk** [comment]
Yes, the usb port will be different, but I don't see how it would break. Clearly the ESP32S3 module is OK (else my code would not run), but I cannot see why WLED would have an issue. It may be worth asking on the WLED forums if they have any clue. There really is not a lot to go wrong - it has power supply, an ESP32S3 module, and connection to terminals for LED.

**Comment by revk** [comment]
It may be worth trying to build WLED with the GPIO we use pre-defined?

**Comment by jsouto77** [comment]
> It may be worth trying to build WLED with the GPIO we use pre-defined?

If you would kindly provide one, that would be great. In the meantime ive received some other esp32 chips and can load WLED on them without issues.

**Comment by revk** [comment]
I have no how to build WLED

**Comment by jsouto77** [comment]
Was about to shelf this today and gave it another go. The latest bets flash 4mb S3 worked and i managed to get it work on GPIO 4 for communication.

**Comment by revk** [comment]
Ah good

**Comment by jsouto77** [comment]
Can comfortably say it's a very nice board in its own right. Nice and compact and perfect if you just want a straight forward led controller AND you dont want any extras such a reactive sound etc... Very neat.

My sole opinion is that you should just ship it with WLED  pre-installed. 

As you have some manufacturing setup, I would advise you make something like quinLED for this side of the pond :)

**Comment by revk** [comment]
Thanks for feedback
