### ISSUE TITLE
can't get led strip to light up

### ISSUE THREAD

**Issue by DuplicantWood** [revk/ESP32-LED#8]
Hi i bought this on amazon with an WS2812B led strip ([specifically this one](https://www.amazon.co.uk/YUNBO-Individually-Addressable-NO-Waterproof-Flexible/dp/B07Q9KCC6M/)). I've got it powered on and connected to  my internet but the led strip won't light up. 

I've set the led amount in settings and tried using the basic effects but nothing happens.

Any idea what i could be doing wrong? 

Thanks

**Comment by DuplicantWood** [comment]
Nevermind it's a faulty led strip (just tested with an arduino) 

Sorry about that, this is a very cool product.

**Comment by revk** [comment]
Thanks
